NavboardTTY = "/dev/ttyO1"
MotorboardTTY = "/dev/ttyO0"
RollPID = [ 0.04, 0.0, 0.002 ]
PitchPID = [ 0.04, 0.0, 0.002 ]
#disabled, needs magnotometer to work well
YawPID = [ 0.04, 0.0, 0.0 ]
AltitudePID = [ 0.3, 0.03, 0.03 ]
HttpAddr = ":80"